version: '3.8'
services:
  backend:
    image: node:22.15-alpine
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    depends_on:
      - mongo
  mongo:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
